#%RAML 1.0
title: Loans overdue status
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: API for loans overdue status
    content: <b>API for fetching overdue status of loans</b>

traits:
  validate: !include raml-util/traits/validation.raml

/circulation/loans/overdue-status:
    description: "Check if the loans are overdue, and calculate overdue minutes for every loan that is. The strategy for calculation depends on the configuration of applicable Overdue Fine Policy."
  post:
    is: [validate]
    body:
      application/json:
        type: !include loans-overdue-status-request.json
    responses:
      200:
        body:
          application/json:
            type: !include loans-overdue-status-response.json
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
