#%RAML 1.0
title: Loan overdue status
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: API for loan overdue statuses
    content: <b>API for fetching overdue statuses of loans</b>

traits:
  language: !include raml-util/traits/language.raml

types:
  errors: !include raml-util/schemas/errors.schema

/circulation/loans/overdue-statuses:
    description: "Check if the loans are overdue, and calculate overdue minutes for every loan that is. The strategy for calculation depends on the configuration of applicable Overdue Fine Policy."
  get:
    responses:
      200:
        body:
          application/json:
            type: !include loans-overdue-statuses.json
      400:
        description: "The loan is closed"
      404:
        description: "The loan is not found"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
